package com.browseros.app

/**
 * BuildConfig stub for compilation
 * Actual BuildConfig is generated by Gradle during build
 */
object BuildConfig {
    const val DEBUG = false
    const val APPLICATION_ID = "com.browseros.app"
    const val BUILD_TYPE = "release"
    const val VERSION_CODE = 1
    const val VERSION_NAME = "1.0.0"
}
